"""Regenerate parity fixtures from a local market-sim checkout.

market-sim is a private reference. This script does not clone or fetch it.
Point MARKET_SIM_PATH at a checkout you already have (the directory that
contains the market_sim package) and run:

    MARKET_SIM_PATH=/path/to/market-sim python scripts/regenerate_fixtures.py

The files under tests/fixtures/ are simulated outputs, not measured prices.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures"
NOTE = (
    "Simulated defaults from the private market-sim reference. "
    "Not measured prices. Regenerated by scripts/regenerate_fixtures.py. "
    "Do not edit by hand."
)


def main() -> None:
    source = os.environ.get("MARKET_SIM_PATH", "").strip()
    if len(sys.argv) > 1:
        source = sys.argv[1]
    if not source:
        raise SystemExit(
            "Set MARKET_SIM_PATH to a local checkout of the private market-sim "
            "reference. This script does not fetch it."
        )
    sys.path.insert(0, str(Path(source).resolve()))
    from market_sim.clearing import PoolView, clear_day_ahead, clear_realtime
    from market_sim.controller import corridor_cap, step_base
    from market_sim.floor import conditional_floor_boost, floor_per_hour, reserve_per_hour
    from market_sim.orders import Order, Rung
    from market_sim.upgrade import commit_upgrade_pass

    FIXTURES.mkdir(parents=True, exist_ok=True)
    _write("floor.json", _floor(floor_per_hour, reserve_per_hour))
    _write("boost.json", _boost(conditional_floor_boost))
    _write("controller.json", _controller(step_base, corridor_cap))
    _write("realtime.json", _realtime(Order, Rung, PoolView, clear_realtime))
    _write("day_ahead.json", _day_ahead(Order, Rung, PoolView, clear_day_ahead, commit_upgrade_pass))
    _write("engine_realtime.json", _engine_realtime(Order, Rung, PoolView, clear_realtime))
    print(f"wrote fixtures in {FIXTURES}")


def _floor(floor_per_hour, reserve_per_hour) -> dict:
    rows = [
        ("0.070", "0.1834", "1.05", "1999"),
        ("0.80", "0.1834", "1.05", "4500"),
        ("1.275", "0.1419", "1.3", "35625"),
        ("130", "0.1419", "1.2", "3000000"),
    ]
    cases = []
    for kw, tariff, overhead, capex in rows:
        floor = floor_per_hour(float(kw), float(tariff), float(overhead), float(capex), 0.0, 0.50, 0.0)
        reserve = reserve_per_hour(floor, 0.08, 1.3)
        cases.append(
            {
                "input": {
                    "loaded_kw": kw,
                    "tariff_per_kwh": tariff,
                    "overhead": overhead,
                    "capex": capex,
                    "residual": "0",
                    "u": "0.50",
                    "host_margin": "0",
                    "take": "0.08",
                    "boost": "1.3",
                },
                "expected": {"floor": _num(floor), "reserve": _num(reserve)},
            }
        )
    return _doc(cases)


def _boost(conditional_floor_boost) -> dict:
    cases = []
    for utilization in ("0", "0.35", "0.40", "0.45", "0.55", "0.9", "1"):
        got = conditional_floor_boost(
            float(utilization), 1.3, 0.35, 0.55, hysteresis=0.03, direction=1
        )
        cases.append(
            {
                "input": {
                    "utilization": utilization,
                    "b_max": "1.3",
                    "u_low": "0.35",
                    "u_high": "0.55",
                    "hysteresis": "0.03",
                    "direction": 1,
                },
                "expected": _num(got),
            }
        )
    return _doc(cases)


def _controller(step_base, corridor_cap) -> dict:
    steps = []
    for base, util, delta, reserve, cap in (
        ("1.00", "1.0", "0.025", "0.50", "10.0"),
        ("0.40", _num(4 / 6), "0.10", "0.01", "10.0"),
        ("2.00", "0.0", "0.025", "1.00", "8.0"),
        ("1.00", "1.0", "0.025", "1.00", "3.00"),
    ):
        got = step_base(float(base), float(util), 0.70, float(delta), float(reserve), float(cap))
        steps.append(
            {
                "input": {
                    "base": base,
                    "utilization": util,
                    "target": "0.70",
                    "delta": delta,
                    "reserve": reserve,
                    "cap": cap,
                },
                "expected": _num(got),
            }
        )
    prices = ["2.0", "3.0", "4.0"]
    corridor = corridor_cap(1.0, [float(price) for price in prices], kappa=3, lambda_cap=1.5)
    return _doc(
        {
            "steps": steps,
            "corridor": {
                "input": {
                    "reserve": "1.0",
                    "day_ahead_prices": prices,
                    "kappa": "3",
                    "lambda": "1.5",
                },
                "expected": _num(corridor),
            },
        }
    )


def _realtime(Order, Rung, PoolView, clear_realtime) -> dict:
    orders = [
        _order(Order, Rung, "A", "A", [("H", "1.50")], lottery=2),
        _order(Order, Rung, "B", "B", [("H", "1.20"), ("L", "0.60")], lottery=3),
        _order(Order, Rung, "C", "C", [("H", "1.10"), ("L", "0.50")], tip="0.05", lottery=11),
        _order(Order, Rung, "D", "D", [("H", "0.90"), ("L", "0.50")], lottery=4),
        _order(Order, Rung, "E", "E", [("H", "1.30")], tip="0.10", lottery=10),
        _order(Order, Rung, "F", "F", [("H", "1.05"), ("L", "0.45")], lottery=1),
        _order(Order, Rung, "G", "G", [("L", "0.70")], lottery=5),
        _order(Order, Rung, "J", "J", [("L", "0.42")], lottery=6),
    ]
    pools = [
        {"pool_id": "H", "supply": "4", "base": "1.00", "reserve": "0.01"},
        {"pool_id": "L", "supply": "6", "base": "0.40", "reserve": "0.01"},
    ]
    result = clear_realtime(
        [_sim_order(Order, Rung, spec) for spec in orders],
        _sim_pools(PoolView, pools),
        share_cap=0.25,
        tip_cap=0.10,
    )
    return _doc(
        {
            "share_cap": "0.25",
            "tip_cap": "0.10",
            "orders": orders,
            "pools": pools,
            "expected": _clearing(result),
        }
    )


def _day_ahead(Order, Rung, PoolView, clear_day_ahead, commit_upgrade_pass) -> dict:
    orders = [
        _order(Order, Rung, "Big", "Big", [("X", "9.0")], lottery=1),
        _order(Order, Rung, "S", "S", [("X", "5.0"), ("H", "5.0")], lottery=2),
        _order(Order, Rung, "U", "U", [("H", "4.0"), ("L", "4.0")], lottery=3),
        _order(Order, Rung, "Other", "Other", [("L", "2.0")], lottery=4),
    ]
    pools = [
        {"pool_id": "X", "supply": "1", "base": "1.0", "reserve": "1.0"},
        {"pool_id": "H", "supply": "1", "base": "1.0", "reserve": "1.0"},
        {"pool_id": "L", "supply": "1", "base": "1.0", "reserve": "1.0"},
    ]
    sim_orders = [_sim_order(Order, Rung, spec, kind="day_ahead") for spec in orders]
    sim_pools = _sim_pools(PoolView, pools)
    downward = clear_day_ahead(sim_orders, sim_pools, share_cap=None)
    upgraded, gains = commit_upgrade_pass(sim_orders, downward, sim_pools, None)
    body = {
        "share_cap": None,
        "orders": orders,
        "pools": pools,
        "expected_down": _clearing(downward),
        "expected_upgrade": {"gains": gains, "fills": _fills(upgraded)},
    }
    return _doc(body)


def _engine_realtime(Order, Rung, PoolView, clear_realtime) -> dict:
    orders = [
        _engine_order("A", "A", [("H", 150)], lottery=2),
        _engine_order("B", "B", [("H", 120), ("L", 60)], lottery=3),
        _engine_order("C", "C", [("H", 110), ("L", 50)], tip=5, lottery=11),
        _engine_order("D", "D", [("H", 90), ("L", 50)], lottery=4),
        _engine_order("E", "E", [("H", 130)], tip=10, lottery=10),
        _engine_order("F", "F", [("H", 105), ("L", 45)], lottery=1),
        _engine_order("G", "G", [("L", 70)], lottery=5),
        _engine_order("J", "J", [("L", 42)], lottery=6),
    ]
    pools = [
        _engine_pool("H", supply="4", base=100, reserve=50, trail="0.80"),
        _engine_pool("L", supply="6", base=40, reserve=20, trail="0.50"),
    ]
    sim_orders = [
        _order(Order, Rung, "A", "A", [("H", "1.50")], lottery=2),
        _order(Order, Rung, "B", "B", [("H", "1.20"), ("L", "0.60")], lottery=3),
        _order(Order, Rung, "C", "C", [("H", "1.10"), ("L", "0.50")], tip="0.05", lottery=11),
        _order(Order, Rung, "D", "D", [("H", "0.90"), ("L", "0.50")], lottery=4),
        _order(Order, Rung, "E", "E", [("H", "1.30")], tip="0.10", lottery=10),
        _order(Order, Rung, "F", "F", [("H", "1.05"), ("L", "0.45")], lottery=1),
        _order(Order, Rung, "G", "G", [("L", "0.70")], lottery=5),
        _order(Order, Rung, "J", "J", [("L", "0.42")], lottery=6),
    ]
    result = clear_realtime(
        [_sim_order(Order, Rung, spec) for spec in sim_orders],
        _sim_pools(
            PoolView,
            [
                {"pool_id": "H", "supply": "4", "base": "1.00", "reserve": "0.50"},
                {"pool_id": "L", "supply": "6", "base": "0.40", "reserve": "0.20"},
            ],
        ),
        share_cap=0.25,
        tip_cap=0.10,
    )
    return _doc(
        {
            "request": {
                "round_id": "rt-illustrative",
                "round_start": "2026-09-25T00:15:00Z",
                "pools": pools,
                "orders": orders,
            },
            "expected_fills": _fills(result),
        }
    )


def _order(Order, Rung, order_id, org_id, rungs, *, tip="0", lottery=0, hours="1"):
    return {
        "order_id": order_id,
        "org_id": org_id,
        "lottery": lottery,
        "tip": tip,
        "hours": hours,
        "rungs": [{"pool_id": pool, "max": price} for pool, price in rungs],
    }


def _sim_order(Order, Rung, spec, *, kind="realtime"):
    return Order(
        spec["order_id"],
        spec["org_id"],
        tuple(Rung(rung["pool_id"], max_price=float(rung["max"]), willingness=float(rung["max"])) for rung in spec["rungs"]),
        quantity=float(spec["hours"]),
        tip=float(spec["tip"]),
        lottery=spec["lottery"],
        kind=kind,
    )


def _sim_pools(PoolView, pools):
    return {
        pool["pool_id"]: PoolView(
            pool["pool_id"],
            supply=float(pool["supply"]),
            base=float(pool["base"]),
            reserve=float(pool["reserve"]),
        )
        for pool in pools
    }


def _engine_pool(pool_id, *, supply, base, reserve, trail):
    return {
        "pool_id": pool_id,
        "class_id": "class",
        "region": "lab",
        "supply_hours": supply,
        "n_hosts": 8,
        "reserve_cents": reserve,
        "prev_base_cents": base,
        "trailing_util_24h": trail,
        "boost": {"applied": "1.3", "direction": 0, "prev_trail": None},
    }


def _engine_order(order_id, org_id, rungs, *, tip=0, lottery=0, hours="1"):
    return {
        "order_id": order_id,
        "org_id": org_id,
        "lottery": lottery,
        "tip_cents": tip,
        "hours": hours,
        "rungs": [{"pool_id": pool, "max_cents": cents} for pool, cents in rungs],
    }


def _clearing(result) -> dict:
    return {
        "passes": result.passes,
        "scarce": {pool_id: pool.scarce for pool_id, pool in sorted(result.pools.items())},
        "fills": _fills(result),
    }


def _fills(result) -> list[dict]:
    return [
        {
            "order_id": fill.order_id,
            "org_id": fill.org_id,
            "pool_id": fill.pool_id,
            "rung_index": fill.rung_index,
            "hours": _num(fill.quantity),
            "pay": _num(fill.pay_per_hour),
        }
        for fill in result.fills
    ]


def _doc(cases) -> dict:
    return {"simulated": True, "note": NOTE, "cases": cases}


def _num(value: float) -> str:
    return format(value, ".17g")


def _write(name: str, payload: dict) -> None:
    path = FIXTURES / name
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
